<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-04T21:55:45 IST" name="Suite" finished-at="2025-04-04T21:56:19 IST" duration-ms="33788">
    <groups>
    </groups>
    <test started-at="2025-04-04T21:55:45 IST" name="Test" finished-at="2025-04-04T21:56:19 IST" duration-ms="33788">
      <class name="tests.FormFields">
        <test-method is-config="true" signature="start()[pri:0, instance:tests.FormFields@7b98f307]" started-at="2025-04-04T21:55:46 IST" name="start" finished-at="2025-04-04T21:56:00 IST" duration-ms="14533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="submitFormOnlyMandatory()[pri:1, instance:tests.FormFields@7b98f307]" started-at="2025-04-04T21:56:00 IST" name="submitFormOnlyMandatory" description="TC_AN_FF_01" finished-at="2025-04-04T21:56:04 IST" duration-ms="3668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitFormOnlyMandatory -->
        <test-method signature="submitFormAllFields()[pri:2, instance:tests.FormFields@7b98f307]" started-at="2025-04-04T21:56:04 IST" name="submitFormAllFields" description="TC_AN_FF_02" finished-at="2025-04-04T21:56:10 IST" duration-ms="5917" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitFormAllFields -->
        <test-method signature="submitFormWithoutMandatory()[pri:3, instance:tests.FormFields@7b98f307]" started-at="2025-04-04T21:56:10 IST" name="submitFormWithoutMandatory" description="TC_AN_FF_03" finished-at="2025-04-04T21:56:18 IST" duration-ms="8015" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitFormWithoutMandatory -->
        <test-method signature="skippedTest()[pri:4, instance:tests.FormFields@7b98f307]" started-at="2025-04-04T21:56:18 IST" name="skippedTest" description="TC_AN_FF_03.2" finished-at="2025-04-04T21:56:18 IST" duration-ms="70" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this test case because of some condition.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this test case because of some condition.
at tests.FormFields.skippedTest(FormFields.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skippedTest -->
        <test-method signature="myFail()[pri:5, instance:tests.FormFields@7b98f307]" started-at="2025-04-04T21:56:18 IST" name="myFail" description="TC_AN_FF_03.3" finished-at="2025-04-04T21:56:18 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at tests.FormFields.myFail(FormFields.java:73)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFail -->
        <test-method is-config="true" signature="end()[pri:0, instance:tests.FormFields@7b98f307]" started-at="2025-04-04T21:56:18 IST" name="end" finished-at="2025-04-04T21:56:19 IST" duration-ms="740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- tests.FormFields -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
